app/konradgnat/blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('blog', views.PostList.as_view(), name='blog'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('books', views.BooksList.as_view(), name='books'),
    path('books/<slug:slug>/', views.BookDetail.as_view(), name='book_detail'),
    path('projects', views.ProjectsList.as_view(), name='projects'),
    path('projects/<slug:slug>/', views.ProjectDetail.as_view(), name='project_detail'),
]

app/konradgnat/konradgnat/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from blog import views
from django.conf.urls import url

# get quotes from here	
# https://konradgnat.com/quotes-api/quotes/

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quotes-api/', include('quotesApi.urls')),
    path('', include('blog.urls')),
    # re_path(r'^api/post/$', views.post_list),
    # re_path(r'^api/post/([a-z])$', views.post_detail),
    # re_path(r'^api/rooms/$', views.room_list),
    # re_path(r'^api/rooms/([a-z])$', views.room_detail),
    # re_path(r'^api/rooms/([a-z])/messages$', views.room_messages)
]

app/konradgnat/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

BOOK_STATUS = (
    (0, "Want to read"),
    (1, "Reading currently"),
    (2, "Read"),
)

BOOK_FORMAT = {
    (0, "Print"),
    (1, "Ebook"),
    (2, "Audiobook"),
}

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    tags = TaggableManager()
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    preview = models.CharField(max_length=200)
    created_on = models.DateTimeField(null=True, blank=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

class ChatUser(models.Model):
    user_name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.user_name

class Message(models.Model):
    username = models.ForeignKey(ChatUser, on_delete=models.CASCADE)
    message = models.CharField(max_length=250, unique=True)
    pub_date = models.DateField()

    def __str__(self):
        return self.message

    def get_user(self):
        return "\n".join([u.user_name for u in self.username.all()])
class Room(models.Model):
    room_name = models.CharField(max_length=200, unique=True)
    users = models.ManyToManyField(ChatUser)
    messages = models.ManyToManyField(Message)

    def __str__(self):
        return self.room_name

    def get_users(self):
        return "\n".join([u.user_name for u in self.users.all()])

    def get_messages(self):
        return "\n".join([m.message for m in self.messages.all()])

class Book(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    image_url = models.CharField(max_length=200)
    tags = TaggableManager()
    author = models.CharField(max_length=200)
    updated_on = models.DateTimeField(auto_now= True)
    created_on = models.DateTimeField(auto_now= True)
    read_on = models.DateField(null=True, blank=True)
    content = models.TextField()
    preview = models.CharField(max_length=200)
    status = models.IntegerField(choices=STATUS, default=0)
    book_status = models.IntegerField(choices=BOOK_STATUS, default=0)
    book_format = models.IntegerField(choices=BOOK_FORMAT, default=0)

    class Meta:
        ordering = ['-read_on']

    def __str__(self):
        return self.title
class Project(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    status = models.IntegerField(choices=STATUS, default=0)
    image_url = models.CharField(max_length=200)
    tags = TaggableManager()
    updated_on = models.DateTimeField(auto_now= True)
    built_on = models.DateTimeField(null=True, blank=True)
    content = models.TextField()

app/konradgnat/blog/views.py
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
from django.http import HttpResponse
from django.template import loader

from django.views import generic 

from .models import Post
from .models import Room
from .models import Message
from .models import Book
from .models import Project
from .serializers import *

def home(request):
    template_name = 'index.html'
    template = loader.get_template('index.html')
    context = {}
    return HttpResponse(template.render(context, request))
class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog.html'

class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

class BooksList(generic.ListView):
    queryset = Book.objects.filter(status=1).order_by('-read_on')
    template_name = 'books.html'

class BookDetail(generic.DetailView):
    model = Book
    template_name = 'books/book_detail.html'

class ProjectsList(generic.ListView):
    queryset = Project.objects.filter(status=1).order_by('-built_on')
    template_name = 'projects.html'

class ProjectDetail(generic.DetailView):
    model = Project
    template_name = 'projects/project_detail.html'

# TODO: create project templates

# TODO: create a React front end for a chat room
# TODO: consider if this is a good idea, might prefer to scrap this chat room project

# @api_view(['GET', 'POST'])
# def post_list(request):
#     if request.method == 'GET':
#         data = Post.objects.all()

#         serializer = PostSerializer(data, context={'request': request}, many=True)

#         return Response(serializer.data)

#     elif request.method == 'POST':
#         serializer = PostSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(status=status.HTTP_201_CREATED)
            
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# @api_view(['PUT', 'DELETE'])
# def post_detail(request, pk):
#     try:
#         post = Post.objects.get(pk=pk)
#     except Post.DoesNotExist:
#         return Response(status=status.HTTP_404_NOT_FOUND)

#     if request.method == 'PUT':
#         serializer = PostSerializer(post, data=request.data,context={'request': request})
#         if serializer.is_valid():
#             serializer.save()
#             return Response(status=status.HTTP_204_NO_CONTENT)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#     elif request.method == 'DELETE':
#         post.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)


# @api_view(['GET', 'POST'])
# def room_list(request):
#     if request.method == 'GET':
#         data = Room.objects.all()

#         serializer = RoomSerializer(data, context={'request': request}, many=True)

#         return Response(serializer.data)

#     elif request.method == 'POST':
#         serializer = RoomSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(status=status.HTTP_201_CREATED)
            
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

app/konradgnat/konradgnat/templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="en">
{% load static %}

<head>
  <script>console.time("start_to_end");</script>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Konrad Gnat | Portfolio</title>
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">

  <!-- bootstrap css and js library -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- material ui css and js library -->
  <link href="//cdn.muicss.com/mui-0.10.3/css/mui.min.css" rel="stylesheet" type="text/css" />
  <script src="//cdn.muicss.com/mui-0.10.3/js/mui.min.js"></script>

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Abel|Catamaran|Josefin+Sans" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <script type="text/javascript" src="{% static 'bundle.js' %}"></script>
  <!-- google analytics -->
  <script>
    (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-88237019-2', 'auto');
    ga('send', 'pageview');
  </script>
</head>

<body>
  <!-- Navigation bar -->
  <div id="website_wrapper">
    <nav id="home" class="nav navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <div id="menuToggle" class="container-button" type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
          </div>
          <a class="navbar-brand" href="{% url 'home' %}"><i class="fa fa-code" aria-hidden="true"></i></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}#about">About</a></li>
            <li><a href="{% url 'home' %}#projects">Projects</a></li>
            <li><a href="{% url 'home' %}#contact">Contact</a></li>
            <li><a href="{% url 'blog' %}">Blog</a></li>
            <li><a href="{% url 'books' %}">Bookshelf</a></li>
            <!--<li><a target="_blank" href="./resume.pdf">Resume</a></li>-->
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}

    <!-- Contact Section -->
    <section>
      <div class="container-fluid">
        <div class="cont section-3">

          <div class="row" id="contact">
            <div class="col-xs-12 titles">
              <h2>Contact</h2>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-8 col-md-offset-2">
              <form class=" displayBox form-horizontal" action="https://formspree.io/kgnat77@gmail.com" method="POST">
                <fieldset>
                  <div class="form-group">
                    <label for="message_name" class="col-xs-4 col-md-4 control-label">Name</label>
                    <div class="input-group">
                      <input name="message_name" placeholder="Name" class="form-control" type="text">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="message_email" class="col-xs-4 col-md-4 control-label">Email</label>
                    <div class="input-group">
                      <input name="message_email" placeholder="E-Mail Address" class="form-control" type="text">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="message_content" class="col-xs-4 col-md-4 control-label">Message</label>
                    <div class="input-group">
                      <textarea name="message_content" cols="10" rows="6" placeholder="Message" class="form-control"
                        type="text"></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-md-4 control-label"></label>
                    <div class="col-md-4">
                      <input type="submit" value="send" class="submit-button">
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer id="footer">
      <div class="container-fluid">
        <div class="row">
          <div class="socialMedia" id="social-media">
            <ul>
              <li>
                <a target="_blank" href="https://github.com/kon-rad">
                  <i class="fa fa-github fa-2x" aria-hidden="true"></i>
                </a>
              </li>
              <li>
                <a target="_blank" href="https://www.instagram.com/__kon__rad__/?hl=en">
                  <i class="fa fa-instagram fa-2x" aria-hidden="true"></i>
                </a>
              </li>
              <li>
                <a target="_blank" href="https://www.linkedin.com/in/konrad-gnat">
                  <i class="fa fa-linkedin fa-2x" aria-hidden="true"></i>
                </a>
              </li>
              <li>
                <a target="_blank" href="https://twitter.com/konrad_gnat">
                  <i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </div>
</body>

</html>

app/konradgnat/konradgnat/templates/blog.html
{% extends "base.html" %}
{% block content %}

<!-- Content Section -->
<section class="blog">
  <div class="jumbotron_image__blog-header">
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="page-header">
          <h1>Articles</h1>
        </div>
        <div class="blog_text">
          <section class="blog_links">
            <div class="well well-lg">

              <!-- Blog Entries Column -->
              {% for post in post_list %}
              <div class="card mb-4">
                <div class="card-body">
                  <h2 class="card-title">{{ post.title }}</h2>
                  <p class="card-text text-muted h6 blog__date">{{ post.created_on|date:'m-d-Y' }} </p>
                  <p class="card-text">{{ post.preview }}</p>
                  <a href="{% url 'post_detail' post.slug  %}" class="">Read More &rarr;</a>
                </div>
              </div>
              {% endfor %}

            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</section>

{%endblock%}

app/konradgnat/konradgnat/templates/book_detail.html
{% extends 'base.html' %} {% block content %}

<section class="book">
  <div class="jumbotron_image__book-header">
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <div class="page-header">
          <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        </div>
        <div class="book_text">
          <p class="text-muted">{{ book.created_on|date:'m-d-Y' }}</p>
          <p class="card-text ">{{ object.content | safe }}</p>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

app/konradgnat/konradgnat/templates/books.html
{% extends "base.html" %}
{% block content %}

<!-- Content Section -->
<section class="books">
  <div class="jumbotron_image__books-header">
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <div class="page-header">
          <h1>Bookshelf</h1>
        </div>
        <div class="books__description">
          <p>A special place for some of the books I have read and loved.</p>
        </div>
        <div class="books_text">
          <section class="books_links">
            <div class="well well-lg">

              <div class="container">
                <div class="row">

                  <!-- books Entries Column -->
                  {% for book in book_list %}
                  <div class="card col-sm-4">
                    <div class="card-body">
                      <div class="book__heading">
                        <img src="/static/images/books/{{ book.image_url }}" alt="" class="books__img">
                        <h2 class="card-title">{{ book.title }}</h2>
                      </div>
                      <div class="book__body">
                        <p class="card-text text-muted h6 books__date">{{ book.read_on|date:'m-d-Y' }} </p>
                        <p class="card-text">{{ book.preview }}</p>
                        <!-- TODO: implement tags -->
                        <!-- <div class="book__tags">
                          tags:
                          {{ book.tags }}
                        </div> -->
                        <!-- TODO: Implement detail page -->
                        <!-- <a class="mui-btn mui-btn--raised" href="/books/{{ book.slug }}">read more</a> -->
                      </div>
                    </div>
                  </div>
                  {% endfor %}

                </div>
              </div>

            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</section>

{%endblock%}

app/konradgnat/konradgnat/templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!-- Main Swiper -->
<div class="swiper-container swiper-container--main section-1" id="mainSlider">
  <div class="swiper-wrapper swiper-wrapper--main">
    <div class="swiper-slide swiper-slide--main">
      <div class="mainSlider__inner_wrapper">
        <h1>Konrad Gnat</h1>
        <h2>Software Engineer</h2>
      </div>
    </div>
    <!-- <div class="swiper-slide swiper-slide--main">
      <div class="mainSlider__inner_wrapper">
        <p>"<span id="quote" class="modal__quote"></span>"</p>
        <span id="author" class="modal__author"></span>
        <br />
        <div class="quote__buttons">
          <span id="newQuote" class="modal__new_quote">another quote</span>
          <span id="copyQuoteToClipboard" class="modal__copy_quote">copy to clipboard</span>
        </div>
      </div>
    </div>
    <div class="swiper-slide swiper-slide--main">
      <div class="mainSlider__inner_wrapper">
        <h2>Tech: JavaScript, React, Unity, Swift, Python</h2>
      </div>
    </div> -->
  </div>
  <!-- Add Pagination -->
  <!-- <div class="swiper-pagination "></div> -->
  <!-- Add Arrows -->
  <!-- <div style="display:none;" class="swiper-button-next swiper-button-next--main"></div>
  <div style="display:none;" class="swiper-button-prev swiper-button-prev--main"></div> -->
</div>
<!-- Curved line -->
<div class="curvedLine__wrapper">
  <svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
    <path d="M0.00,49.98 C173.53,171.20 363.71,-73.52 500.00,49.98 L500.00,150.00 L0.00,150.00 Z"
      style="stroke: none; fill: #e5e9eb;">
    </path>
  </svg>
</div>
<!-- Projects -->
<section id="projects">
  <div class="container-fluid">
    <div class="row titles">
      <div class="col-xs-12">
        <h2 id="projects-title">Projects</h2>
      </div>
    </div>
  </div>
  <div class="portfolio-wrapper">
    <!-- Project #1 -->
    <ul>
      <li class="portfolio-item" onclick="">
        <div class="imgWrap">
          <div class="imgDescription">
            <h2>Tank Battalion</h2>
            <p>A 2D game built from scratch with vanilla JavaScript and the canvas element. It includes
              a single player and live multi player modes. Play it at the link below!</br>
              Node, Express, Jade, Hosted on Digital Ocean</p> </br>
            <p><a target="_blank" href="http://tankbattalion.gnonous.com" class="button">Live Site</a> | <a
                target="_blank" href="https://github.com/kon-rad/tank-battalion" class="button">See the Code</a></p>
          </div>
        </div>
        <img data-webp="{% static 'images/webp/tank.webp' %}" src="{% static 'images/tank.png' %}" alt=""
          class="img-responsive">
      </li>
      <li class="portfolio-item" onclick="">
        <div class="imgWrap">
          <div class="imgDescription">
            <h2>Reads Planet A NodeJS, React, MongoDB App</h2>
            <p>Features user sign in, create, edit, delete posts and comments. Follow users and edit profile. Passport
              library for
              authentication and EJS templating engine. Data on books is received from Google Books
              API.</br>
              Node, Express, React, Flow, Enzyme, MongoDB</p> </br>
            <p><a target="_blank" href="http://readsplanet.gnonous.com/" class="button">Visit Page</a> | <a
                target="_blank" href="https://github.com/kon-rad/readbooks" class="button">Github</a></p>
          </div>
        </div>
        <img data-webp="{% static 'images/webp/read-books.webp' %}" src="{% static 'images/read-books.png' %}" alt=""
          class="img-responsive">
      </li>
      <li class="portfolio-item" onclick="">
        <div class="imgWrap">
          <div class="imgDescription">
            <h2>Coherent Breathing App</h2>
            <p>Practice coherent breathing technique</p>
            <ul>
              <li>Node</li>
              <li>React</li>
              <li>Redux</li>
              <li>Express</li>
              <li>PassportJS</li>
              <li>Deployed to Digital Ocean</li>
            </ul>
            </br>
            <p>
              <a target="_blank" href="http://coherentbreathing.gnonous.com/" class="button">Live Site</a> | <a
                target="_blank" href="https://github.com/kon-rad/coherentBreathingApp" class="button">See the Code</a>
            </p>
          </div>
        </div>
        <img data-webp="{% static 'images/webp/coherentBreathing.webp' %}"
          src="{% static 'images/coherentBreathing.png' %}" alt="" class="img-responsive">
      </li>
      <li class="portfolio-item" onclick="">
        <div class="imgWrap">
          <div class="imgDescription">
            <h2>YouTube to MP3 Converter</h2>
            <p>Download MP3 file of YouTube videos, specify playback rate from 0.5 to 2.0. Built from scratch, no CRA,
              webpack configured from scratch</p>
            <ul>
              <li>Node</li>
              <li>Express</li>
              <li>React</li>
              <li>Webpack</li>
              <li>Deployed to Digital Ocean</li>
            </ul>
            </br>
            <p><a target="_blank" href="http://addmp3.gnonous.com" class="button"><span>Live Site</span></a> | <a
                target="_blank" href="https://github.com/kon-rad/addMP3.fun" class="button">See the Code</a></p>
          </div>
        </div>
        <img data-webp="{% static 'images/webp/addmp3.webp' %}" src="{% static 'images/addmp3.png' %}" alt=""
          class="img-responsive">
      </li>
      <li class="portfolio-item" onclick="">
        <div class="imgWrap">
          <div class="imgDescription">
            <h2>GifNotes</h2>
            <p>A winning submission completed at GIF Hack 2017 in Palo Alto. Creates a gif from a
              specified segment of video from a YouTube URL.</br>
              Node, Express, jQuery, JavaScript, HTML5, CSS3</p> </br>
            <a target="_blank" href="https://secret-tundra-36331.herokuapp.com/" class="button">Live Site</a>
            <a target="_blank" href="https://github.com/kon-rad/GIFHack2017" class="button">Github</a>
          </div>
        </div>
        <img data-webp="{% static 'images/webp/gifnotes.webp' %}" src="{% static 'images/gifnotes.png' %}" alt=""
          class="project-img img-responsive">
      </li>
      <li class="portfolio-item" onclick="">
        <div class="imgWrap">
          <div class="imgDescription">
            <h2>Crypto Prices</h2>
            <p>This is a simple app that shows latest crypto currency prices.
              This could have been built with just a front end, but it was an interesting exercise in developing with
              Django</br>
              Django, React, Coinbase API. It is hosted on a digital ocean droplet with an Nginx server.</p> </br>
            <a target="_blank" href="http://cryptoprices.gnonous.com/" class="button"><span style="color:orange">[Under
                Construction 🚧]</span>Live Site</a> |
            <a target="_blank" href="https://github.com/kon-rad/cryptoPrices.Space" class="button">Github</a>
          </div>
        </div>
        <img data-webp="{% static 'images/webp/cryptoprices.webp' %}" src="{% static 'images/cryptoprices.png' %}"
          alt="" class="project-img img-responsive">
      </li>
      <li class="portfolio-item" onclick="">
        <div class="imgWrap">
          <div class="imgDescription">
            <h2>MatchUpGame</h2>
            <p>React app. Hosted on Digital ocean with nodejs back end.</br>
              React, Node</p> </br>
            <a target="_blank" href="http://matchupgame.gnonous.com/" class="button"><span style="color:orange">[Under
                Construction 🚧]</span>Live Site</a> |
            <a target="_blank" href="https://github.com/kon-rad/matchupgame" class="button">Github</a>
          </div>
        </div>
        <img data-webp="{% static 'images/webp/matchupgame.webp' %}" src="{% static 'images/matchupgame.png' %}" alt=""
          class="project-img img-responsive">
      </li>
    </ul>
  </div>
  <div class="additional-projects-conatiner">
    <h3>Client Projects</h3>
    <p>Corporate Kneads:
      <a class="link--blue" href="https://corporatekneads.com/">live site</a>
    </p>
    <p>Nashville Drum Tracks:
      <a class="link--blue" href="http://nashvilledrumtracks.com">live site</a>
    </p>
  </div>
  <div class="additional-projects-conatiner">
    <h3>More Projects</h3>
    <p> Alexa Skill - 'Martha Gellhorn Quotes'
      <a class="link--blue"
        href="https://www.amazon.com/dp/B07B2Q8ZH7/ref=sr_1_1?s=digital-skills&ie=UTF8&qid=1519877246&sr=1-1&keywords=martha+gellhorn">link
        to
        skill on Amazon</a>
      |
      <a class="link--blue" href="https://github.com/kon-rad/MarthaGellhornQuotes-AlexaSkill">github</a>
    </p>
    <p>Scripturally Sound: Code for the Kingdom 2017 Hackathon, Nashville
      <a class="link--blue" href="https://github.com/kon-rad/c4tk">github</a>
    </p>
    <p>Spaceship Shootout: Mad Hacks 2017 Hackathon Project, University of Wisconsin-Madison
      <a class="link--blue" href="https://github.com/kon-rad/spaceships-madhacks-2017">github</a>
    </p>
    <p>Live Sports 360 VR App: Developer Week 2017 Hackathon, San Francisco - Winner Best Video Streaming App
      <a class="link--blue" href="https://github.com/kon-rad/developerWeekHackathon2017">github</a>
    </p>
    <p>FireMixtapeMd: Uncommon Hacks 2017 Hackathon, University of Chicago
      <a class="link--blue" href="https://github.com/kon-rad/uncommonHackathon">github</a>
    </p>
  </div>
</section>
<!-- About -->
<section>
  <div class="container-fluid">
    <div class="row cont" id="about">
      <div class="col-xs-12 titles">
        <h2> About </h2>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row cont section-2">

      <div class="col-xs-12 col-md-8 col-md-offset-2 displayBox">
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div class="about__image_wrapper">
              <img class="about__image" src="{% static 'images/vr_hacker.png' %}" alt="">
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 textBox textContent">
            <span class="textContent">
              My mission is to build apps that push humanity forward. I am
              driven by a passion for learning and finding out where I can provide real value by building things with
              technology. Among my greatest intellectual
              hero's are Buckminster Fuller, John Muir,
              Leonardo Da Vinci, John
              Steinbeck
              and Kahlil Gibran. On any given day I can be found coding applications that push the envelope of
              what's possible
              in VR/AR and web development. When not coding, I enjoy reading and zen meditation.
            </span>
            </br></br>
            <div>
              <span class="uppercase">Languages</span><br>
              Swift, C#, JavaScript, Python, PHP, SQL, Java
            </div>
            <br>
            <span class="uppercase">Frameworks</span><br>
            Django, Symfony, React
            <br>
            <br>
            <span class="uppercase">Technologies</span><br>
            Unity VR Game Development, iOS development, Blender, Git, MySQL, MongoDB, Linux
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{%endblock%}

app/konradgnat/konradgnat/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<section class="blog">
  <div class="jumbotron_image__blog-header">
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <div class="page-header">
          <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        </div>
        <div class="blog_text">
          <p class="text-muted">{{ post.created_on|date:'m-d-Y' }}</p>
          <p class="card-text ">{{ object.content | safe }}</p>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}